export const SITE_SETTINGS_DEFAULTS = {
  /* ════════════════════════════════════════════════════════════
     HOME PAGE — All sections editable from Admin CMS
     ════════════════════════════════════════════════════════════ */
  homePage: {
    hero: {
      enabled: true,
      eyebrow: 'Est. 2008 — Handcrafted in Agra',
      titleLine1: 'Where Craft',
      titleLine2: 'Becomes',
      titleLine3: 'Legacy',
      description: 'Each pair is shaped by sixteen years of mastery — hand-lasted, hand-stitched, and finished to an heirloom standard that only improves with age.',
      primaryButtonText: 'Explore Collection',
      primaryButtonLink: '/products',
      secondaryButtonText: 'Our Process',
      secondaryButtonLink: '#craft',
      image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=1200&h=1600&fit=crop&q=80',
      stats: [
        { label: 'Years', value: 16, suffix: '+' },
        { label: 'Pairs Crafted', value: 48, suffix: 'K+' },
        { label: 'Artisans', value: 12, suffix: '' },
      ],
    },
    marquee: {
      enabled: true,
      text: 'Full-Grain Leather\u2002◆\u2002Goodyear Welt\u2002◆\u2002Hand-Burnished\u2002◆\u2002Free Shipping in India\u2002◆\u2002Lifetime Resoling\u2002◆\u2002Cork Footbed\u2002◆\u2002Handcrafted in Agra',
    },
    collection: {
      enabled: true,
      label: 'Curated Selection',
      title: 'The Collection',
      useRealProducts: true,
      productLimit: 4,
      productSelection: 'latest',
      manualProductIds: [],
    },
    craft: {
      enabled: true,
      label: 'Our Process',
      titleLine1: 'The Art of',
      titleLine2: 'Shoemaking',
      images: [
        { id: 'craft-1', url: 'https://images.unsplash.com/photo-1616486029423-aaa4789e8c9a?w=1200&h=800&fit=crop&q=80', alt: 'Artisan hand-stitching leather' },
        { id: 'craft-2', url: 'https://images.unsplash.com/photo-1616486029423-aaa4789e8c9a?w=1200&h=800&fit=crop&q=80', alt: 'Workshop overview' },
        { id: 'craft-3', url: 'https://images.unsplash.com/photo-1605733160314-4fc7dac4bb16?w=1200&h=800&fit=crop&q=80', alt: 'Shoe lasting process' },
        { id: 'craft-4', url: 'https://images.unsplash.com/photo-1449505278894-297fdb3edbc1?w=1200&h=800&fit=crop&q=80', alt: 'Hand burnishing finish' },
      ],
      features: [
        { num: '01', name: 'Goodyear Welt', desc: 'A 200-year-old construction method that lets the sole be replaced — extending every pair\'s life by decades.' },
        { num: '02', name: 'Hand-Burnished', desc: 'Each shoe is burnished by hand, giving the leather a rich, luminous patina unique to its wearer.' },
        { num: '03', name: 'Cork Insole', desc: 'A natural cork footbed moulds to your foot over time, providing bespoke comfort with every step.' },
        { num: '04', name: 'Full-Grain', desc: 'Only the finest full-grain hides are selected — sourced from heritage tanneries across three continents.' },
      ],
    },
    heritage: {
      enabled: true,
      label: 'Our Heritage',
      titleLine1: 'Crafted in',
      titleLine2: 'Agra',
      description: 'From the city of the Taj Mahal — Agra has been the heart of India\'s leather craft for centuries. SBALI continues this tradition, blending Mughal-era artisanship with contemporary design in every pair we create.',
      image: 'https://images.unsplash.com/photo-1560343090-f0409e92791a?w=1200&h=900&fit=crop&q=80',
      points: [
        { icon: '🏛️', title: 'Heritage City', desc: 'Agra\'s leather craft tradition spans over 400 years, rooted in Mughal artisanship.' },
        { icon: '✋', title: 'Master Craftsmen', desc: 'Our karigars (artisans) carry generations of skill passed down through families.' },
        { icon: '🌿', title: 'Locally Sourced', desc: 'Premium hides sourced from India\'s finest tanneries in Kanpur and Chennai.' },
      ],
    },
    story: {
      enabled: true,
      label: 'Our Story',
      titleLine1: 'Born From',
      titleLine2: 'Passion',
      paragraphs: [
        'Founded in 2008, SBALI started as a small atelier in Agra with a singular vision — to create leather shoes that rival the finest European makers, rooted in Indian craftsmanship.',
        'Today, our twelve artisans continue that tradition. Every pair passes through over 200 hand operations before it earns the SBALI name.',
      ],
      quote: 'A great shoe isn\'t made — it\'s born. Every cut, every stitch, every burnish is a conversation between the artisan and the leather.',
      image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&h=900&fit=crop&q=80',
      ctaText: 'Our Story',
      ctaLink: '/about',
    },
    testimonials: {
      enabled: true,
      items: [
        {
          id: 'testimonial-1',
          text: 'The Langham Oxford is, without exaggeration, the finest shoe I have worn. The leather develops a patina that tells your story. Exceptional.',
          author: 'Arjun Mehta, Mumbai',
          rating: 5,
        },
        {
          id: 'testimonial-2',
          text: 'I\'ve worn bespoke from London and Florence. SBALI stands shoulder to shoulder with the best — at a fraction of the price. Truly remarkable craftsmanship.',
          author: 'Vikram Singh, New Delhi',
          rating: 5,
        },
        {
          id: 'testimonial-3',
          text: 'Every detail speaks of care. From the unboxing ritual to the first step on pavement — this is what luxury should feel like. My fourth pair.',
          author: 'Priya Sharma, Bangalore',
          rating: 5,
        },
      ],
    },
    ctaBanner: {
      enabled: true,
      titleLine1: 'Step Into',
      titleLine2: 'Legacy',
      subtitle: 'Handcrafted to order. Delivered to your door. Free shipping across India.',
      primaryButtonText: 'Shop Collection',
      primaryButtonLink: '/products',
      secondaryButtonText: 'Book an Appointment',
      secondaryButtonLink: '/contact',
    },
  },
  homeSections: {
    heroSection: {
      enabled: true,
      title: 'Step Into',
      subtitle: 'Timeless Elegance',
      description:
        'Discover exquisite handcrafted shoes made with premium materials and timeless craftsmanship. Each pair is a masterpiece designed to elevate your style.',
      primaryButtonText: 'Explore Collection',
      primaryButtonLink: '/products',
      secondaryButtonText: 'Our Story',
      secondaryButtonLink: '/about',
      backgroundGradient: 'from-primary-50 via-brand-cream/20 to-primary-100',
    },
    featuredProducts: {
      enabled: true,
      title: 'Featured Collection',
      description:
        'Explore our handpicked selection of premium shoes crafted for the discerning gentleman.',
      productLimit: 8,
      productSelection: 'latest',
      manualProductIds: [],
      viewAllButtonText: 'View All Products',
      viewAllButtonLink: '/products',
    },
    madeToOrder: {
      enabled: true,
      title: 'Made to Order',
      description:
        'All our shoes are crafted to order, ensuring perfect fit and uncompromising quality. Each pair takes 7-10 business days to create.',
      features: ['Custom Crafted', 'Premium Leather', 'Expert Artisans', '7-10 Days Delivery'],
    },
    newsletter: {
      enabled: true,
      title: 'Join Our Community',
      description:
        'Be the first to know about new collections, exclusive offers, and styling tips.',
      placeholder: 'Enter your email',
      buttonText: 'Subscribe',
    },
    testimonials: {
      enabled: true,
      title: 'What Our Customers Say',
      description: 'Real feedback from customers who wear Sbali every day.',
      items: [
        {
          id: 'testimonial-1',
          quote: 'Exceptional comfort and craftsmanship. The fit is perfect and the finish is premium.',
          name: 'Aarav Mehta',
          role: 'Business Consultant',
        },
        {
          id: 'testimonial-2',
          quote: 'The quality is outstanding. I get compliments every time I wear them.',
          name: 'Rohan Kapoor',
          role: 'Product Manager',
        },
        {
          id: 'testimonial-3',
          quote: 'Stylish, durable, and comfortable enough for long days. Highly recommended.',
          name: 'Nikhil Verma',
          role: 'Architect',
        },
      ],
    },
    brands: {
      enabled: true,
      title: 'Trusted Brand Partners',
      description: 'We collaborate with quality-focused partners and manufacturers.',
      items: [
        { id: 'brand-1', name: 'Sbali Atelier', logoText: 'RA' },
        { id: 'brand-2', name: 'Heritage Line', logoText: 'HL' },
        { id: 'brand-3', name: 'Prime Leather Co.', logoText: 'PL' },
        { id: 'brand-4', name: 'Urban Classics', logoText: 'UC' },
      ],
    },
    categories: {
      enabled: true,
      title: 'Shop by Category',
      description: 'Find footwear by style and occasion.',
      items: [
        { id: 'category-oxfords', name: 'Oxfords', link: '/products?category=oxfords' },
        { id: 'category-loafers', name: 'Loafers', link: '/products?category=loafers' },
        { id: 'category-boots', name: 'Boots', link: '/products?category=boots' },
        { id: 'category-sneakers', name: 'Sneakers', link: '/products?category=sneakers' },
      ],
    },
    videoHero: {
      enabled: false,
      title: 'Craftsmanship in Motion',
      description: 'See how each pair is crafted with precision and care.',
      videoUrl: '',
      posterUrl: '',
      primaryButtonText: 'Shop Collection',
      primaryButtonLink: '/products',
      secondaryButtonText: 'Our Story',
      secondaryButtonLink: '/about',
    },
  },
  trustBadges: [
    {
      id: 'badge-quality',
      icon: 'FiAward',
      title: 'Handcrafted Quality',
      description:
        'Each pair is meticulously crafted by skilled artisans using traditional techniques.',
      enabled: true,
      order: 1,
    },
    {
      id: 'badge-shipping',
      icon: 'FiTruck',
      title: 'Free Delivery',
      description: 'Complimentary shipping on all orders within India.',
      enabled: true,
      order: 2,
    },
    {
      id: 'badge-materials',
      icon: 'FiShield',
      title: 'Premium Materials',
      description: 'Only the finest leather and materials for lasting comfort and style.',
      enabled: true,
      order: 3,
    },
  ],

  bannerSystem: {
    enabled: true,
    banners: [],
  },
  announcementBar: {
    enabled: false,
    text: 'Grand Opening Sale - Get 20% off on all products with code GRAND20',
    backgroundColor: '#10b981',
    textColor: '#ffffff',
    link: '/products',
    dismissible: true,
  },
  contactInfo: {
    address: '123 Shoe Street, Fashion District, Mumbai 400001',
    phone: '+91 123 456 7890',
    email: 'support@sbali.in',
    showAddress: true,
    showPhone: true,
    showEmail: true,
  },
  socialLinks: [
    { platform: 'facebook', url: '', enabled: false, order: 1 },
    { platform: 'twitter', url: '', enabled: false, order: 2 },
    { platform: 'instagram', url: '', enabled: true, order: 3 },
  ],
  contactPage: {
    title: 'Get in Touch',
    subtitle: "Have a question or need help? We're here for you!",
    formEnabled: true,
    businessHours: [
      { day: 'Monday - Friday', hours: '9:00 AM - 6:00 PM' },
      { day: 'Saturday', hours: '10:00 AM - 4:00 PM' },
      { day: 'Sunday', hours: 'Closed' },
    ],
    supportCard: {
      title: 'Quick Answers',
      description:
        'Looking for immediate help? Check out our FAQ section for answers to common questions.',
      ctaText: 'Visit FAQ',
      ctaLink: '/faq',
    },
  },
  faqPage: {
    title: 'Frequently Asked Questions',
    subtitle: 'Find answers to common questions about Sbali',
    categories: [
      {
        id: 'faq-orders',
        name: 'Orders & Payments',
        order: 1,
        enabled: true,
        questions: [
          {
            id: 'faq-orders-1',
            question: 'What payment methods do you accept?',
            answer:
              'We accept major credit/debit cards, UPI, net banking, and Cash on Delivery where available.',
            order: 1,
            enabled: true,
          },
          {
            id: 'faq-orders-2',
            question: 'Can I modify or cancel my order?',
            answer:
              'You can modify or cancel shortly after placing your order from the My Orders page.',
            order: 2,
            enabled: true,
          },
        ],
      },
      {
        id: 'faq-shipping',
        name: 'Shipping & Delivery',
        order: 2,
        enabled: true,
        questions: [
          {
            id: 'faq-shipping-1',
            question: 'How long does delivery take?',
            answer: 'Most deliveries complete in 3-7 business days depending on location.',
            order: 1,
            enabled: true,
          },
        ],
      },
    ],
    supportTitle: 'Still have questions?',
    supportDescription: 'Our customer support team is here to help you.',
    supportPrimaryText: 'Contact Support',
    supportPrimaryLink: '/contact',
    supportSecondaryText: 'Email Us',
    supportSecondaryLink: 'mailto:support@sbali.in',
  },
  footerContent: {
    brand: {
      name: 'Sbali',
      description:
        'Premium handcrafted shoes made with timeless craftsmanship and finest materials.',
      logo: '',
    },
    columns: [
      {
        id: 'footer-quick-links',
        title: 'Quick Links',
        order: 1,
        links: [
          { text: 'Home', url: '/', enabled: true, order: 1 },
          { text: 'Products', url: '/products', enabled: true, order: 2 },
          { text: 'About Us', url: '/about', enabled: true, order: 3 },
          { text: 'Contact', url: '/contact', enabled: true, order: 4 },
        ],
      },
      {
        id: 'footer-customer-service',
        title: 'Customer Service',
        order: 2,
        links: [
          { text: 'Track Order', url: '/orders', enabled: true, order: 1 },
          { text: 'Returns & Exchange', url: '/returns', enabled: true, order: 2 },
          { text: 'Shipping Info', url: '/shipping', enabled: true, order: 3 },
          { text: 'FAQ', url: '/faq', enabled: true, order: 4 },
        ],
      },
    ],
    legal: {
      copyrightText: 'All rights reserved.',
      links: [
        { text: 'Privacy Policy', url: '/privacy', enabled: true, order: 1 },
        { text: 'Terms & Conditions', url: '/terms', enabled: true, order: 2 },
      ],
    },
    newsletter: {
      enabled: true,
      title: 'Subscribe to Our Newsletter',
      description: 'Get updates on new products and exclusive offers',
      placeholder: 'Enter your email',
      buttonText: 'Subscribe',
    },
  },
  aboutPage: {
    title: 'About Sbali',
    subtitle: 'Your trusted destination for premium footwear since 2026',
    heroImage: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=1600&h=600&fit=crop&q=80',
    storyImage: 'https://images.unsplash.com/photo-1595341888016-a392ef81b7de?w=800&h=600&fit=crop&q=80',
    storyTitle: 'Our Story',
    storyParagraphs: [
      'Sbali was born from a simple belief: everyone deserves access to quality footwear that combines style, comfort, and durability.',
      'We curate products that match modern lifestyles while maintaining quality and comfort standards.',
      'We partner with trusted manufacturers and brands to bring authentic products at fair prices.',
    ],
    values: [
      {
        id: 'about-value-quality',
        icon: 'check',
        title: 'Quality First',
        description: 'We never compromise on quality. Every product is inspected before reaching you.',
        enabled: true,
        order: 1,
      },
      {
        id: 'about-value-customer',
        icon: 'clock',
        title: 'Customer First',
        description: "Your satisfaction is our priority from browsing to post-purchase support.",
        enabled: true,
        order: 2,
      },
      {
        id: 'about-value-delivery',
        icon: 'lightning',
        title: 'Fast Delivery',
        description: 'We process quickly and deliver reliably across serviceable locations.',
        enabled: true,
        order: 3,
      },
    ],
    differentiatorsTitle: 'What Sets Us Apart',
    differentiators: [
      {
        id: 'about-diff-authentic',
        title: 'Authentic Products',
        description: '100% genuine products from trusted brands and manufacturers.',
        enabled: true,
        order: 1,
      },
      {
        id: 'about-diff-returns',
        title: 'Easy Returns',
        description: 'Hassle-free returns within the eligible return window.',
        enabled: true,
        order: 2,
      },
      {
        id: 'about-diff-payments',
        title: 'Secure Payments',
        description: 'Multiple payment options with robust encryption standards.',
        enabled: true,
        order: 3,
      },
      {
        id: 'about-diff-support',
        title: '24/7 Support',
        description: 'Our support team is available whenever you need assistance.',
        enabled: true,
        order: 4,
      },
    ],
    cta: {
      title: 'Ready to Find Your Perfect Pair?',
      description: 'Explore our collection and step into comfort.',
      primaryButtonText: 'Shop Now',
      primaryButtonLink: '/products',
      secondaryButtonText: 'Contact Us',
      secondaryButtonLink: '/contact',
    },
  },
  shippingPolicy: {
    title: 'Shipping Information',
    subtitle: 'Fast, reliable delivery to your doorstep',
    highlights: [
      { id: 'shipping-highlight-fast', icon: 'lightning', title: 'Fast Delivery', description: '3-7 business days across India' },
      { id: 'shipping-highlight-free', icon: 'check', title: 'Free Shipping', description: 'On orders above Rs 1,000' },
      { id: 'shipping-highlight-track', icon: 'chat', title: 'Track Order', description: 'Real-time tracking updates' },
    ],
    shippingCosts: [
      { id: 'shipping-cost-free', orderValue: 'Above Rs 1,000', cost: 'FREE', deliveryTime: '3-5 business days', badgeText: 'FREE' },
      { id: 'shipping-cost-standard', orderValue: 'Below Rs 1,000', cost: 'Rs 50', deliveryTime: '3-5 business days' },
      { id: 'shipping-cost-express', orderValue: 'Express Delivery', cost: 'Rs 150', deliveryTime: '1-2 business days', note: 'Available in select metro cities' },
    ],
    deliveryZones: [
      { id: 'shipping-zone-metro', zone: 'Metro Cities', cities: 'Mumbai, Delhi, Bangalore, Chennai, Kolkata, Hyderabad', time: '2-3 business days' },
      { id: 'shipping-zone-tier2', zone: 'Tier 2 Cities', cities: 'Pune, Jaipur, Ahmedabad, Lucknow and more', time: '3-5 business days' },
      { id: 'shipping-zone-others', zone: 'Other Locations', cities: 'Small towns and rural areas', time: '5-7 business days' },
    ],
    processing: {
      summary: 'All orders are processed within 24-48 hours (excluding weekends and holidays).',
      points: ['In-stock items: 24-48 hours', 'Made-to-order: 5-7 business days plus delivery', 'Customized products: 7-10 business days plus delivery'],
    },
    trackingSteps: ['Log in to your account', 'Go to My Orders', 'Open the order details', 'View live tracking and ETA'],
    shippingPartners: ['Blue Dart', 'Delhivery', 'FedEx', 'DTDC'],
    deliveryIssues: {
      notHome: 'Delivery partners attempt 2-3 times before holding at the nearest courier office.',
      delayed: 'If delivery is delayed, contact support with your order number for immediate help.',
    },
    international: {
      enabled: false,
      message: 'Currently we only ship within India.',
      waitlistText: 'Contact us to join the international shipping waitlist.',
    },
    support: {
      title: 'Questions About Shipping?',
      description: 'Our support team is here to help with shipping-related queries.',
      primaryText: 'Contact Support',
      primaryLink: '/contact',
      secondaryText: 'View FAQ',
      secondaryLink: '/faq',
    },
  },
  returnsPolicy: {
    title: 'Return & Refund Policy',
    subtitle: 'We want you to love your purchase. If not, we make returns easy.',
    quickSummary: [
      { id: 'returns-summary-window', title: '7-Day Return Window', description: 'Return products within 7 days of delivery.' },
      { id: 'returns-summary-pickup', title: 'Free Pickup', description: 'We collect return shipments from your doorstep.' },
      { id: 'returns-summary-refund', title: 'Full Refund', description: 'Refunds are processed within 5-7 business days after inspection.' },
    ],
    eligibilityCriteria: [
      'Returned within 7 days of delivery',
      'Unused and in original condition',
      'Original packaging, tags, and labels intact',
      'No visible signs of wear or damage',
      'Original invoice included',
    ],
    nonReturnableItems: [
      'Products marked as Final Sale or Non-Returnable',
      'Worn, damaged, or altered products',
      'Products without original packaging or tags',
      'Products returned after the return window',
    ],
    returnProcess: [
      { id: 'return-step-1', step: 1, title: 'Initiate Return', description: 'Go to your orders and select Return.' },
      { id: 'return-step-2', step: 2, title: 'Select Reason', description: 'Share reason and details for the return.' },
      { id: 'return-step-3', step: 3, title: 'Schedule Pickup', description: 'Choose a convenient pickup window.' },
      { id: 'return-step-4', step: 4, title: 'Get Refund', description: 'Receive refund once quality checks are complete.' },
    ],
    refundPolicy: {
      processingTime: '5-7 business days after successful inspection.',
      methods: [
        'Online payments: refunded to original payment method',
        'Cash on Delivery: bank transfer after details confirmation',
        'Store credit: optional instant credit where applicable',
      ],
      note: 'Bank processing may add 2-3 business days.',
    },
    exchangePolicy: [
      'Return the original product first',
      'Place a new order for required item/size',
      'Contact support if you need expedited replacement help',
    ],
    damagedProductPolicy: {
      intro: 'If you receive a damaged or defective product:',
      steps: [
        'Take clear photos of product and packaging',
        'Contact support within 24 hours of delivery',
        'Share photos over support email',
        'Pickup and refund/replacement will be prioritized',
      ],
      note: 'For damaged products, normal return window constraints may be relaxed after verification.',
    },
    support: {
      title: 'Need Help with a Return?',
      description: 'Our customer service team is here to assist with returns or refunds.',
      primaryText: 'Contact Support',
      primaryLink: '/contact',
      secondaryText: 'Email Us',
      secondaryLink: 'mailto:support@sbali.in',
    },
  },
  maintenanceMode: {
    enabled: false,
    title: 'We will be back soon',
    message: 'We are performing scheduled maintenance. Thank you for your patience.',
    estimatedEndTime: '',
    allowAdminAccess: true,
    allowedIPs: [],
  },
  theme: {
    mode: 'light',
    headerVariant: 'centered',
    centerLogo: true,
    primaryColor: '#3B2F2F',
    secondaryColor: '#E5D3B3',
    accentColor: '#c9a96e',
    accentHoverColor: '#a07840',
    backgroundColor: '#fafaf9',
    textColor: '#1c1917',
    bodyTextColor: '#8a7460',
    mutedTextColor: '#5c3d1e',
    borderColor: '#e8e0d0',
    subtleBgColor: '#f2ede4',
    colorModes: {
      light: {
        primaryColor: '#3B2F2F',
        secondaryColor: '#E5D3B3',
        backgroundColor: '#fafaf9',
        textColor: '#1c1917',
      },
      dark: {
        primaryColor: '#C9B18F',
        secondaryColor: '#6F5A43',
        backgroundColor: '#111827',
        textColor: '#F9FAFB',
      },
    },
    fontFamily: 'var(--font-inter)',
    borderRadius: '0.5rem',
  },
};

export const SITE_SETTING_KEYS = Object.keys(SITE_SETTINGS_DEFAULTS);
